#!/bin/sh -e

for patch in *.patch; do
    patch -p0 < "$patch"
done

# Build qemu-system* binaries dynamically linked
./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --enable-debug-info \
    --disable-gtk \
    --disable-docs \
    --enable-sdl \
    --enable-kvm \
    --disable-pie \
    --enable-curses \
    --disable-user \
    --disable-linux-user \
    --enable-system

pwd
cp /var/db/kiss/repo/kiss/qemu/configure .

make
make DESTDIR="$1" PREFIX=/usr install
